name: Check PR - spek2
on:
  pull_request:
    paths:
      - 'spek-dsl/**'
      - 'spek-runtime/**'
      - 'spek-runner-junit5/**'
      - 'integration-test/**'
      - 'build.gradle.kts'
      - 'buildSrc/build.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/check-pr-core.yaml'

jobs:
  integration_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            task: spekLinuxTest spekJvmTest
          - os: macos-latest
            task: spekMacosTest spekJvmTest
          - os: windows-latest
            task: spekWindowsTest spekJvmTest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: integration-test
          arguments: ${{ matrix.task }} -PexcludeIdePlugins -i
  runner_junit5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: spek-runner-junit5:check -PexcludeIdePlugins
