name: CI
on:
  push:
    branches:
      - 2.x
    tags:
      - '*'

jobs:
  deploy_spek2:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            arguments: spek-dsl:bintrayUpload spek-runtime:bintrayUpload spek-runner-junit5:bintrayUpload --stacktrace -PexcludeIdePlugins
          - os: windows-latest
            arguments: spek-dsl:bintrayUpload spek-runtime:bintrayUpload --stacktrace -PexcludeIdePlugins
          - os: macos-latest
            arguments: spek-dsl:bintrayUpload spek-runtime:bintrayUpload --stacktrace -PexcludeIdePlugins
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Checkout submodules
        uses: snickerbockers/submodules-init@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: ${{ matrix.arguments }}
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

  deploy_ij_plugin:
    strategy:
      matrix:
        ij_sdk: [IJ193, IJ201, IJ202]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: spek-ide-plugin-intellij-idea:publishPlugin -Pij.version=${{ matrix.ij_sdk }}
        env:
          HUB_API_TOKEN: ${{ secrets.HUB_API_TOKEN }}

  deploy_as_plugin:
    strategy:
      matrix:
        as_sdk: [AS35, AS36, AS40]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
      - run: git fetch --depth=1000 origin +refs/tags/*:refs/tags/*
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: spek-ide-plugin-android-studio:publishPlugin -Pas.version=${{ matrix.as_sdk }}
        env:
          HUB_API_TOKEN: ${{ secrets.HUB_API_TOKEN }}
