sudo: false

language: java

matrix:
  include:
  - jdk: openjdk8
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.0.7
  - jdk: openjdk8
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.1.61
  - jdk: openjdk8
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.2.50
  - jdk: openjdk8
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.3.50
  - jdk: openjdk8
    env: TERM=dumb KOTLIN_VERSION=1.0.7
  - jdk: openjdk8
    env: TERM=dumb KOTLIN_VERSION=1.1.61
  - jdk: openjdk8
    env: TERM=dumb KOTLIN_VERSION=1.2.50
  - jdk: openjdk8
    env: TERM=dumb KOTLIN_VERSION=1.3.50


env:
  matrix:
  - TERM=dumb

install:
 - true

script:
  - ops/mockMakerInline.sh
  - ./gradlew clean
  - ./gradlew assemble
  - ./gradlew test -i

notifications:
  email: false
