language: java

jdk:
  - oraclejdk8

script: ./gradlew build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "0x+45V1Ny6umN/+biHN1whMY5KGx6iEfRqR0lCIN3hpiJpl9w5cUiKC0mKFXWcdReagUC8io1Dogxvhy5HKKenBjKWJfW3DyLdKs4jOluwu++v4DWbnWYuS0VwHvCQjapV3IYKT0tACB3GkcWVyxvqN4JDuSN0zwW6knAmr9VEXlyYSXvBRzRZI1b1qQImwXxfEnu/XP4Fax41oAnKS2hJn8yYmXcX8OBaTKHqU8OzjrwhE51CZfMtiyVzyL7JvEUX9EQ2Jlg8k1Z7NPfxc0TXDtm8q/1u+ewb7u5qtJ8Th2U8GknQuhFtndC5f3PnmEolfwLWMum3cmQdSPJaLCw8u7eowed8Uq6ZjKAih5oWOsgEIsELqh0TzTVWTkG0VMzTL82jUMwpL7hga7gLtfFtxa8Me3DjakiG/gBa2fIAlhdH+5s7m0wAwoutRzBRctJ01UZdEd7ftB+1T6dpIuOeEfdQrs2JPPiRh22hTSh9tJ2dsmSQFb7/tUVCIU/9RvOCKbYeM7pQ/6J5HxmYyvflYLadJQfBihcumy7hZvCj08kdd/c4dHBXwi9LcMme+r3NM9llVakwnHdO1I3ON1UqRQAGC1LeZjc+mya2hQNrdv9X+hqG4MwNJW3bR6JWpX3D5S4iiSiU0uMmEbuakNh+01YW9u77GisNB7T8p+yiY="
    - secure: "aJLbTxnR+7vpgHrr0QF42JgBZGUEkF6b3TZKya68TOZLD5Xt8NHzbPuwyrFfWj3/4R8GdW4x3FrZRP9nmn9Tlw+w4EqfSp/N+T7PMpNaVg0wVg94NLs3XLNABC7w3Mum4fLjgL/z8Rm/8+/+I/hRpCpGqQ/6jgn4DFD7MNhmbUFSuFEECVsjetRgWvZuymHCcEXC2hwrO+0h5Ug0+DU+ln3tcXpp6fNyQRCCsh2oLRJFZJbeR9UhS8vL/OzRqTSgzLFeXWNhpzr/b6Oi6tvMla6ZEoQKxShoZQfCAmJc4H1ql+IBCm8pjDdvNq3m7PnB2Bz/Jb6lqYgYqktPBuUALuoJmF72uD1X+8NDmkUGKKq/8VO49VxeGCAPuxJHmrbDFenNAVKqS4MYYO2MkNwD8Ja5CPgKZtG4LTvTGyoOU72vzFrJgoHXJ2Qlqc4xE9sC8dwkO1/rb0d3naV4BRH57tR+bA4ubvRKoBmI5TokOeBxQeVVj+2wtEyZdMgNDfjBFOztNahAsgJry7fX/ngKR+XQxgJ9kFpvWGFqICYG3Bdj5NKwLL6wo0lK9wye6O7YbmN5yVtlZRMF/6oXfGPmLWQb1CbH4bXo/owAh6NBNnchLXIMTzvFy9++7SBrEFqPgDbCkhu4aPmQrbttVa58v+R+kfwkmXkAkdNxV2nTVh0="

notifications:
  email: false

sudo: false
